name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: install dependencies
        run: pnpm install
      - name: type check
        run: pnpm type-check
      - name: format check
        run: pnpm format:check
      - name: graphql codegen check
        run: pnpm gen-gql:check
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build
